service: aws-lambda-layer-sharp
frameworkVersion: '>=1.34.0 <2.0.0'
publish: false
provider:
  name: aws
  runtime: nodejs14.x
  profile: testSls
  region: eu-west-1

layers:
  sharp:
    description: Sharp nodejs imaging library as a layer
    package:
      artifact: ./layers/sharp/out/sharp-0.27.2-aws-lambda-linux-x64-node-14.16.0.zip
    compatibleRuntimes:
      - nodejs14.x
    allowedAccounts:
      - '*'
